aws-ebs-csi-driver:
  controller:
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::679441504692:role/ebs_csi_role
  storageClasses: [ ]
  # Add StorageClass resources like:
  # - name: ebs-sc
  #   # annotation metadata
  #   annotations:
  #     storageclass.kubernetes.io/is-default-class: "true"
  #   # label metadata
  #   labels:
  #     my-label-is: supercool
  #   # defaults to WaitForFirstConsumer
  #   volumeBindingMode: WaitForFirstConsumer
  #   # defaults to Delete
  #   reclaimPolicy: Retain
  #   parameters:
  #     encrypted: "true":